---
- hosts: all
  vars:
    tmux_version: 3.2a-4ubuntu0.2
    tmux_plugin_base_dir: ~/.config/tmux/plugins/
    plugin_catppuccin_version: v2.1.3
  tasks:
    - name: Install tmux terminal multiplexer
      become: true
      ansible.builtin.package:
        name: tmux={{ tmux_version }}
        state: present

    - name: Install catppuccin themes (visual schemas)
      ansible.builtin.git:
        repo: https://github.com/catppuccin/tmux.git
        dest: '{{ tmux_plugin_base_dir }}/catppuccin/tmux'
        refspec: '{{ plugin_catppuccin_version }}'

    - name: Save tmux.conf
      ansible.builtin.copy:
        src: tmux.conf
        dest: ~/.tmux.conf
        mode: '644'
