---
- hosts: all
  vars:
    fzf_version: v0.65.2
  tasks:
    - name: Download nvim pkg 
      ansible.builtin.uri:
        url: https://github.com/neovim/neovim/releases/download/v0.11.4/nvim-linux-x86_64.tar.gz
        follow_redirects: all
        force: true
        dest: /tmp/nvim.tar.gz

    - name: Unarchive nvim 
      become: true
      ansible.builtin.unarchive:
        src: /tmp/nvim.tar.gz
        dest: /opt

    - name: Create nvim dir structure
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory
        mode: 0755

    - name: Copy local folder to remote 
      ansible.builtin.copy: 
        src: ./lua
        dest: ~/.config/nvim/ 
        mode: 0644

    - name: Create nvim main conf
      ansible.builtin.template:
        src: init.lua
        dest: ~/.config/nvim/init.lua
        mode: '744'
