---
- hosts: all
  tasks:
    - name: Download git_delta diff highlighter from git releases (by tag)
      ansible.builtin.uri:
        url: https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_amd64.deb
        follow_redirects: all
        force: true
        dest: /tmp/git_delta.deb
    
    - name: Install git_delta from local package
      become: true
      ansible.builtin.apt:
        deb: /tmp/git_delta.deb

    - name: Remove git_delta installer
      ansible.builtin.file:
        path: /tmp/git_delta.deb
        state: absent

    - name: Add git-delta conf
      ansible.builtin.copy:
        src: git_conf
        dest: ~/
        mode: 0644

    - name: Download color themes for git-delta
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/dandavison/delta/main/themes.gitconfig
        dest: ~/git_conf/themes.gitconfig